### ISSUE TITLE
Model named "Transaction" breaks SQLite

### ISSUE THREAD

**Issue by Kilo-Loco** [aws-amplify/amplify-ios#1232]
**Describe the bug**
If you name your model "Transaction", SQLite throws an error:

```
2021-05-14 15:21:03.801849-0700 bad-name[75507:11180230] [logging] near "Transaction": syntax error in "create table if not exists Transaction (
  "id" text primary key not null,
  "value" text
);"
2021-05-14 15:21:03.803693-0700 bad-name[75507:11180230] [AWSDataStorePlugin] The operation couldn’t be completed. (Amplify.DataStoreError error 8.)
2021-05-14 15:21:03.803790-0700 bad-name[75507:11180230] [logging] near "Transaction": syntax error in "select count(id) from Transaction where id = ?"
failure(DataStoreError: The operation couldn’t be completed. (SQLite.Result error 0.)
Recovery suggestion: The operation couldn’t be completed. (SQLite.Result error 0.)
Caused by:
near "Transaction": syntax error (code: 1))
```

**To Reproduce**
1. Create a model named "Transaction" (https://sandbox.amplifyapp.com/schema-design/4236af71-d0bb-47fa-9455-ddce75bcf525)
2. Generate code locally
3. Configure Amplify (only DataStore is needed)
4. Attempt to save instance of `Transaction`

**Expected behavior**
Models should be saved, regardless of name.

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.9.2
 - Amplify Categories:
   - [ ] Analytics
   - [ ] API
   - [ ] Auth
   - [x] DataStore
   - [ ] Predictions
   - [ ] Storage
 - Dependency Manager: SPM
 - Swift Version: 5.4
 - CLI Version: 4.51.0
 - Xcode Version: 12.5 (12E262)

**Is this a regression (i.e. was this working before a version upgrade?)
I think this may have worked before, but can't be sure.

**Device Information (please complete the following information):**
 - Device: iPhone 11 Simulator
 - iOS Version: iOS 14.5
 - Specific to simulators: No, this error occurs on devices as well

**Comment by kjones** [comment]
[xkcd](https://xkcd.com/327/) -- Sorry, couldn't resist. 🤷🏻

**Comment by rajeshmani27** [comment]
suggestions for resolving the bug
1) Highlight the concept of reserved words to avoid in the documentation and the list of words NOT to use in table/field naming in the FAQ so that the user is aware of it
2) Incorporate reserved words check for table and field naming in the admin ui
3) Ideally, remove commonly used words like Transaction from the reserved words list

**Comment by royjit** [comment]
This should be fixed by the PR https://github.com/aws-amplify/amplify-ios/pull/1233 and will be available in the next release.

**Comment by lawmicha** [comment]
i believe this was released in https://github.com/aws-amplify/amplify-ios/releases/tag/v1.9.3 please let us know if you are still seeing issues

**Comment by tobitech** [comment]
@lawmicha I just upgraded to `v1.10.0` and I'm still experiencing this issue. My model is name Transaction and I keep getting this error `[logging] near "Transaction": syntax error in "select
  "root"."id" as "id", "root"."amount" as "amount", "root"."description" as "description"
from Transaction as "root""
 DataStoreError: The operation couldn’t be completed. (SQLite.Result error 0.)
Recovery suggestion: The operation couldn’t be completed. (SQLite.Result error 0.)
Caused by:
near "Transaction": syntax error (code: 1)`

**Comment by tobitech** [comment]
@royjit This still has the `pending release` label, wondering if it has been released 'cause I still experience this?

**Comment by tobitech** [comment]
@Kilo-Loco did you get this to work?

**Comment by lawmicha** [comment]
there's another PR that will fix this https://github.com/aws-amplify/amplify-ios/pull/1485 please track that PR, and should be released in the next amplify version 1.16.1 or greater
