### ISSUE TITLE
[DataStore] 'modelSynced' event is emitted prior to sync process finishing for the given model

### ISSUE THREAD

**Issue by Jordan-Nelson** [aws-amplify/amplify-ios#1446]
### Describe the bug

The [modelSynced event](https://docs.amplify.aws/lib/datastore/datastore-events/q/platform/ios/#modelsynced) is emitted prior to sync process finishing for the given model, and the value for `added` does not match the total number of models that should have been synced.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create an app that uses DataStore with cloud sync. Seed ~10,000 models
2. In the app, subscribe to the `modelSynced` event. Log the info from this event when it occurs.
3. Subscribe to the mutation events from the publisher for the given model. Log the info from these events.
4. Start the app
5. Observe that the `added` count in the `modelSynced` event does not match the total number of models that are (eventually) synced.
6. Observe that there are mutation events from the publisher for the given model after the `modelSynced` event is received.
```

### Expected behavior

When the modelSynced event is received with `isFullSync: true`, the following should be true:
- The sync process for that model should be complete
- The value for `added` should match the total number of models that exist in the cloud
- The publisher should not emit additional create events for the model

### Amplify Framework Version

1.14.0

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

6.1.0

### Xcode version

13.0

### Relevant log output

```shell
I recorded logs that show each event from the publisher and each modelSynced event. They are too big to include in github.
```

### Is this a regression? (i.e. was this working before a version upgrade)

The issue is present in v1.13.0 and v.1.14.0. However, the modelSynced event is consistently emitted earlier with version v1.14.0.

### Device

iPhone 11 (physical device)

### iOS Version

14.7

**Comment by Jordan-Nelson** [comment]
I observed this with a large dataset, but the issue seems to be present with small data sets as well.

**Comment by lawmicha** [comment]
- looks like `ModelSyncedEventEmitter` is based on events from `InitialSyncOrchestrator` and `IncomingEventReconciliationQueue`.
- It looks like InitialSyncOperation will enqueue 1000 items before emitting 1 event each for each enqueued. The emitter uses this event as "recordsReceived" count. This should happen in the first ten seconds since 1 API call is <1s, and so ten 1k items will be added to the reconciliationQueue and 10k events will be emitted for enqueued.
- the reconciliationQueue will create a ReconcileAndLocalSaveOperation with the 1k items, reconcile the items as dropped or applied, which the emitter uses for "reconciledReceived" count

**Comment by lawmicha** [comment]
Scenario 1: Terminate App while syncing. Local SQL has 3k/10k items before terminating. Re-run the app
```
Start ObserveQuery
Initial Query
modelSynced: ModelSyncedEvent(modelName: "Post", isFullSync: false, isDeltaSync: true, added: 0, updated: 0, deleted: 0)
ObserveQuery item count 3853, isSynced: true
```

**Comment by lawmicha** [comment]
this should be fixed with https://github.com/aws-amplify/amplify-ios/pull/1454

**Comment by Jordan-Nelson** [comment]
With #1454, I still see a ModelSyncedEvent emit before the final MutationEvent has emitted. It happens maybe half of the time with a data set of 200 Blogs. When the issue occurs, all but one MutationEvent will emit, then the ModelSyncedEvent emits, and then the final MutationEvent emits. The last two events are emitted less than a millisecond apart, but logs show the last MutationEvent comes in after the ModelSyncedEvent about half of the time.

To see this I added logs to the following two locations:


1. Added the following lines after 138 below
```swift
let date = Date()
print("[Sync Debug iOS] dispatchModelSyncedEvent, modelName: \(mutationEvent.modelName), timeInterval: \(date.timeIntervalSince1970)")
```

https://github.com/aws-amplify/amplify-ios/blob/d639291b084f1f7e33b0b541934f4b7905086344/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/InitialSync/ModelSyncedEventEmitter.swift#L135-L143


2. Added the following lines after 189 below
```swift
let date = Date()
print("[Sync Debug iOS] mutationEvent, modelName: \(mutationEvent.modelName), timeInterval: \(date.timeIntervalSince1970)")
```
https://github.com/aws-amplify/amplify-ios/blob/d639291b084f1f7e33b0b541934f4b7905086344/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/AWSDataStorePlugin.swift#L189-L191

With those logs added, these were the logs I captured.

<details>

[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.886386
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.891798
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.895718
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.89941
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.920723
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.926729
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.931172
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.935127
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.939074
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.943069
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.946795
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.950773
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.971488
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.975531
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.978949
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.983594
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.987812
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.993596
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001039.99842
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.021085
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.027652
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.0324268
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.036458
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.0403528
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.045471
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.04934
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.070005
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.098486
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.1199598
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.12402
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.1323729
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.136621
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.1411781
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.145557
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.148806
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.1687531
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.172766
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.1758919
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.185738
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.189242
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.192523
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.195829
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.199531
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.221335
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.226301
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.2310538
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.236559
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.240417
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.244916
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.2696738
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.274111
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.282033
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.28583
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.290051
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.293987
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.297224
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.3006182
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.323024
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.3278031
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.332149
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.3357549
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.3390288
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.3427072
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.3458772
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.370455
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.374325
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.382313
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.385645
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.388804
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.392071
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.395107
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.398391
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.418767
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.424024
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.427884
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.431598
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.434863
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.4380279
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.441165
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.444442
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.4478211
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.450849
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.471647
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.475055
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.483624
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.4870272
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.490715
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.494241
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.497685
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.500947
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.5242062
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.530909
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.534935
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.538155
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.541537
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.544773
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.5481648
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.551368
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.5721478
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.575547
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.583992
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.587769
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.59115
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.594489
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.597701
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.6014209
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.623856
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.628137
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.632268
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.635898
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.639804
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.644037
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.6691852
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.675571
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.7190042
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.7233028
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.726608
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.729749
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.733636
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.7368898
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.740145
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.743692
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.746932
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.750277
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.770323
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.773615
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.77653
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.779906
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.783128
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.799643
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.820523
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.825807
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.828847
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.832553
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.83611
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.839356
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.842647
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.845484
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.848532
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.85145
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.873025
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.8768969
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.887876
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.891471
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.895344
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.8988981
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.9209108
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.925994
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.934187
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.943371
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.948025
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.971291
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.9759479
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.9876518
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.9914842
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.9948869
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001040.99838
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.018906
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.0235271
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.0272121
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.0304642
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.03471
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.0387259
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.041901
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.045212
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.048285
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.051291
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.072125
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.075773
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.087733
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.091212
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.094363
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.097662
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.100982
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.1258888
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.13055
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.134725
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.1381521
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.1413531
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.144683
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.1479058
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.151263
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.1717691
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.174914
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.1846871
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.187871
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.191201
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.194577
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.197614
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.2007818
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.223176
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.227768
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.232665
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.236762
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.2413979
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.2453141
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.24866
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.268423
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.2725348
[Sync Debug iOS] dispatchModelSyncedEvent, modelName: Blog, timeInterval: 1634001041.275763
[Sync Debug iOS] mutationEvent, modelName: Blog, timeInterval: 1634001041.275816

</details>
